services:
  econecta-landing:
    build: .
    container_name: econecta-landing
    restart: always
    networks:
      - econecta-network
    # NO exponemos puertos aquí, el reverse-proxy se encarga de eso

networks:
  econecta-network:
    external: true
