version: "3.8"

services:
  # El servicio de tu aplicación
  app:
    build: . # Construye la imagen usando el Dockerfile en la carpeta actual
    restart: always
    # No exponemos el puerto, nginx se comunicará internamente

  # El servicio del reverse proxy con SSL en puerto 3000
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80" # Puerto 80 para validación de certificados Let's Encrypt
      - "3000:3000" # Puerto 3000 con SSL para tu dominio
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app

  # Servicio de Certbot para certificados SSL
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
