server {
    listen 80;
    listen [::]:80;
    server_name econecta.io www.econecta.io;

    # Clave para que Certbot pueda validar
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Temporalmente puede dejar la redirección, pero la clave es el 'location' anterior
    location / {
        return 301 https://$host$request_uri;
    }
}